name: Build and push image for the proxy
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      aws-account-id:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: ${{ secrets.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.project }}-ecr-repo-nginx:latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/${{ inputs.project }}-github-actions-role
          aws-region: ${{ inputs.aws-region }}

      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Nginx Docker image
        id: build-nginx-image
        uses: docker/build-push-action@v4
        with:
          context: ./containers/nginx
          file: ./containers/nginx/Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE_URI }}
